name: CI/CD Test per PR.
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - "!releases/**"
env:
  GOVER: 1.23.3

jobs:
  unittest:
    runs-on: sdcio-action-runners
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOVER }}
      - run: go test -cover ./...
        env:
          CGO_ENABLED: 0
